"""Headless TurtleBot3 world + AMCL, and nothing else.

Deliberately localisation-only: the full Nav2 stack would put a controller on
/cmd_vel and fight the session driver for the robot. AMCL is pointed at
/scan_amcl so the dropout relay sits in front of it.
"""
import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import ExecuteProcess, IncludeLaunchDescription, TimerAction
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node

TB3_GAZEBO = get_package_share_directory("turtlebot3_gazebo")
NAV2 = get_package_share_directory("nav2_bringup")
GAZEBO_ROS = get_package_share_directory("gazebo_ros")


def generate_launch_description() -> LaunchDescription:
    world = "/session/params/world.sdf"   # generated by make_world.py
    # LOCTRIAGE_MODEL_SDF lets the slip sweep spawn a model whose tyres really slip in the
    # physics solver. Unset, this is byte for byte the stock waffle, so the control arm of
    # the sweep and every earlier recording use exactly the same robot.
    sdf = os.environ.get("LOCTRIAGE_MODEL_SDF") or os.path.join(
        TB3_GAZEBO, "models", "turtlebot3_waffle", "model.sdf")
    urdf = os.path.join(NAV2, "urdf", "turtlebot3_waffle.urdf")
    with open(urdf) as fh:
        robot_description = fh.read()

    gzserver = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(os.path.join(GAZEBO_ROS, "launch", "gzserver.launch.py")),
        launch_arguments={"world": world, "verbose": "false"}.items(),
    )

    state_pub = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        parameters=[{"use_sim_time": True, "robot_description": robot_description}],
    )

    spawn = ExecuteProcess(
        cmd=["ros2", "run", "gazebo_ros", "spawn_entity.py",
             "-entity", "waffle", "-file", sdf, "-x", "-2.0", "-y", "-0.5", "-z", "0.01"],
        output="screen",
    )

    localization = TimerAction(
        period=12.0,   # AMCL needs the robot spawned and TF flowing before it starts
        actions=[IncludeLaunchDescription(
            PythonLaunchDescriptionSource(os.path.join(NAV2, "launch", "localization_launch.py")),
            launch_arguments={
                "map": os.path.join(NAV2, "maps", "turtlebot3_world.yaml"),
                "use_sim_time": "true",
                "params_file": "/session/params/localization.yaml",
                "autostart": "true",
            }.items(),
        )],
    )

    return LaunchDescription([gzserver, state_pub, spawn, localization])
