"""Assemble the case log's evidence, leaving the verdicts blank.

Everything mechanical is filled in here: which detector fired, when, at what
peak, against which declared expectation. The `outcome` column stays empty on
purpose -- the rubric grades it as author-assessed, and a script that guessed it
would be the exact self-grading problem the rubric exists to prevent.

Usage: build_case_log.py <synthetic-bag> <real-bag> > docs/case-log.md
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
VENV = HERE.parent / ".venv" / "bin"


def detections(bag: Path, config: Path) -> list[dict]:
    out = Path("/tmp/_cl.json")
    subprocess.run([str(VENV / "loctriage"), "--config", str(config), "detect", str(bag),
                    "--json", str(out)], capture_output=True, check=True)
    return json.loads(out.read_text())


def truth(bag: Path) -> list[dict]:
    r = subprocess.run([str(VENV / "python"), str(HERE / "ground_truth.py"), str(bag)],
                       capture_output=True, text=True, check=True)
    return json.loads(r.stdout)


def window(dets: list[dict], a: float, b: float, pad: float = 2.0) -> list[dict]:
    return [d for d in dets if a - pad <= d["start_s"] <= b + pad]


def main() -> None:
    syn, real = Path(sys.argv[1]), Path(sys.argv[2])
    cfg_syn = HERE / "out" / "detectors.sim.yaml"
    cfg_real = HERE.parent / "config" / "detectors.yaml"

    sd, rd = detections(syn, cfg_syn), detections(real, cfg_real)
    gt = truth(syn)

    print("# Case log\n")
    print("Graded against `docs/case-log-rubric.md`, which was fixed and committed **before** any of")
    print("this output existed. The `outcome` column is author-assessed and is stated as such; the")
    print("citation column is mechanical and reproducible by anyone with the recordings.\n")
    print("Every `expected` value below was declared in the recording script before the run, not")
    print("chosen after reading the result.\n")

    print("## Rows from the controlled recording\n")
    print("Faults injected deliberately, tagged live on `/incident_marker` at the moment they")
    print("happened, so ground truth shares a clock with the signals.\n")
    print("| # | Event | Declared | Detected by | Peak | Window | Outcome | Notes |")
    print("|---|---|---|---|---|---|---|---|")
    for i, g in enumerate(gt, 1):
        ins = window(sd, g["t_begin"], g["t_end"])
        names = ", ".join(sorted({d["detector"] for d in ins})) or "**nothing**"
        peak = max((d["peak"] for d in ins), default=0.0)
        exp = g.get("expect", "—")
        print(f"| S{i} | {g['kind']} | {exp} | {names} | {peak:.2f} | "
              f"{g['t_begin']:.0f}–{g['t_end']:.0f}s | _TODO_ | {g.get('note','')[:80]} |")

    print("\n## Rows from the public recording\n")
    print("Real Tiago sensor data. **Provenance: `/scan` and `/tf` are recorded from the robot;**")
    print("**`/amcl_pose` is generated by replaying that real data through Nav2's AMCL.** The bag")
    print("does not contain localisation topics — nobody publishes those pre-recorded, because they")
    print("are an algorithm's output rather than a measurement. No ground truth exists here, so per")
    print("rubric rule 3 no causal claim can be graded better than low-confidence.\n")
    print("| # | Detector | Signal | Peak | Window | Outcome | Notes |")
    print("|---|---|---|---|---|---|---|")
    merged: dict[tuple[str, str], list[dict]] = {}
    for d in rd:
        merged.setdefault((d["detector"], d["key"]), []).append(d)
    for i, ((det, key), ds) in enumerate(sorted(merged.items()), 1):
        pk = max(d["peak"] for d in ds)
        span = f"{min(d['start_s'] for d in ds):.0f}–{max(d['end_s'] for d in ds):.0f}s"
        print(f"| R{i} | {det} | {key} | {pk:.3f} | {span} | _TODO_ | {len(ds)} detection(s) |")

    print("\n## What did not fire, and why that matters\n")
    print("| Detector | On the controlled recording | On the public recording |")
    print("|---|---|---|")
    for det in ("covariance_spike", "tf_jump", "pose_divergence", "scan_gap"):
        s_hit = any(d["detector"] == det for d in sd)
        r_hit = any(d["detector"] == det for d in rd)
        print(f"| {det} | {'fired' if s_hit else '**never fired**'} | "
              f"{'fired' if r_hit else '**never fired**'} |")


if __name__ == "__main__":
    main()
