#!/usr/bin/env bash
# Everything that must be true before this repo is made public.
#
# The build plan calls this a checklist. A checklist under deadline pressure is a
# list of things someone decides to skip; this exits non-zero instead. Run it
# before any push, indefinitely -- not only at first publish.
set -uo pipefail
cd "$(dirname "$0")/.."

FAIL=0
note() { printf '  %-8s %s\n' "$1" "$2"; }
check() { if [ "$1" -eq 0 ]; then note "ok" "$2"; else note "FAIL" "$2"; FAIL=1; fi; }

echo "== identity and naming =="
# The bracket form matches the brand words without this file containing them --
# otherwise the checker fails on itself, which looks exactly like a real leak.
! grep -rilE -e 's[i]llage' -e 'm[a]ssif' . --exclude-dir=.git --exclude-dir=.venv >/dev/null 2>&1
check $? "no brand word in tracked content"

! find . -path ./.git -prune -o -iname '*' -print 2>/dev/null | grep -qiE 's[i]llage|m[a]ssif'
check $? "no brand word in any filename"

! git log --format='%s%n%b%n%an%n%ae' 2>/dev/null | grep -qiE 's[i]llage|m[a]ssif'
check $? "no brand word in commit messages or authorship"

EMAIL=$(git config user.email 2>/dev/null || true)
case "$EMAIL" in
  *[s]illage*|*[m]assif*) note "FAIL" "git email carries a brand: $EMAIL"; FAIL=1 ;;
  "")                 note "FAIL" "no git identity configured"; FAIL=1 ;;
  *)                  note "ok" "git identity is neutral: $EMAIL" ;;
esac

! grep -q PLACEHOLDER LICENSE 2>/dev/null
check $? "LICENSE names a real author"

echo "== binaries and recordings =="
BAGS=$(find . -name '*.mcap' -o -name '*.db3' 2>/dev/null | grep -v '/.git/' | head -40)
if [ -z "$BAGS" ]; then
  note "skip" "no recordings tracked"
else
  BAD=0
  for b in $BAGS; do
    if strings -a "$b" 2>/dev/null | grep -qiE 's[i]llage|m[a]ssif|/home/[a-z]+/Pro|laptop-msi'; then
      note "FAIL" "leak inside $b"; BAD=1
    fi
  done
  check $BAD "no hostname, username or host path inside recordings"
fi

echo "== the claims that must be present =="
grep -qiE 'self-grad|graded by the author|author-assessed' README.md
check $? "self-grading disclosure present in README"

[ -f docs/case-log.md ] && [ "$(grep -c '^| S\|^| R' docs/case-log.md)" -ge 3 ]
check $? "case log has at least 3 rows"

grep -qi 'wrong' docs/case-log.md 2>/dev/null && grep -qi 'low-confidence' docs/case-log.md 2>/dev/null
check $? "case log has a wrong/partial row AND a low-confidence row"

grep -qiE 'generated by replaying|replaying that real data' docs/case-log.md 2>/dev/null
check $? "public recording's provenance stated (topics generated, not recorded)"

echo "== every number resolves to a committed artifact =="
python3 "$(dirname "$0")/check_numbers.py"
check $? "numbers recheck against their artifacts"

echo
if [ "$FAIL" -eq 0 ]; then echo "PRE-PUBLISH: ok"; else echo "PRE-PUBLISH: BLOCKED"; fi
exit $FAIL
